FROM env-quickshell

RUN dnf install -y \
    rpm-build \
    rpmdevtools

ARG WORKING_PROJECT=cpptrace
ARG WORKING_REPO=https://github.com/jeremy-rifkin/cpptrace.git
ARG WORKING_REF=main

WORKDIR /src

RUN git clone "$WORKING_REPO" repo \
    && cd repo \
    && git checkout "$WORKING_REF" \
    && VERSION=$(sed -nE 's/^[[:space:]]*VERSION[[:space:]]+([0-9.]+)$/\1/p' CMakeLists.txt) \
    && git archive \
        --format=tar.gz \
        --prefix=${WORKING_PROJECT}-${VERSION}/ \
        -o /src/repo.tar.gz \
        HEAD \
    && echo "$VERSION" > /src/repo-version \
    && echo "$WORKING_PROJECT" > /src/repo-project

COPY rpm.spec /root/rpmbuild/SPECS/rpm.spec

CMD mkdir -p /rpms \
    && rpmbuild \
        -bb \
        /root/rpmbuild/SPECS/rpm.spec \
        --define "_sourcedir /src" \
        --define "_rpmdir /rpms" \
        --define "_srcrpmdir /rpms" \
        --define "upstream_version $(cat /src/repo-version)" \
        --define "upstream_project $(cat /src/repo-project)"
