name: quickshell

services:
  env:
    image: env-quickshell
    build:
      context: "$HOME/Projects/Podman/Quickshell"
      dockerfile: "$HOME/Projects/Podman/Quickshell/Containerfile"

  cpptrace:
    image: cpptrace-git
    build:
      context: "$HOME/Projects/Podman/Quickshell/cpptrace"
      dockerfile: "$HOME/Projects/Podman/Quickshell/cpptrace/Containerfile"
    volumes:
      - "$HOME/Projects/RPMS:/rpms:Z"

  quickshell:
    image: quickshell-git
    build:
      context: "$HOME/Projects/Podman/Quickshell/quickshell"
      dockerfile: "$HOME/Projects/Podman/Quickshell/quickshell/Containerfile"
    volumes:
      - "$HOME/Projects/RPMS:/rpms:Z"
    depends_on:
      - cpptrace
